config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resource :user, shallow: true do
    resources :claims
    resources :goals
    resources :tribe_items do
      member do
        get 'individual_item'
      end
    end
    get '/total_tribes', to: 'tribe_items#total_tribes'
  end
  get '/update_alpha', to: 'alpha_coin#update_alpha_coin'

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  # Defines the root path route ("/")
  root "landing#index"
end

app/models/claim.rb
class Claim < ApplicationRecord
  belongs_to :user
end

app/controllers/claims_controller.rb
class ClaimsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_user
  before_action :set_claim, only: %i[ show edit update destroy ]
  # GET /claims or /claims.json
  def index
    @claims = @user.claim
  end

  # GET /claims/1 or /claims/1.json
  def show
  end

  # GET /claims/new
  def new
    @claim = @user.claim.build
  end

  # GET /claims/1/edit
  def edit
  end

  # POST /claims or /claims.json
  def create
    @claim = @user.claim.build(claim_params)

    respond_to do |format|
      if @claim.save
        format.html { redirect_to claim_url(@claim), notice: "Claim was successfully created." }
        format.json { render :show, status: :created, location: @claim }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @claim.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /claims/1 or /claims/1.json
  def update
    respond_to do |format|
      if @claim.update(claim_params)
        format.html { redirect_to claim_url(@claim), notice: "Claim was successfully updated." }
        format.json { render :show, status: :ok, location: @claim }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @claim.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /claims/1 or /claims/1.json
  def destroy
    @claim.destroy

    respond_to do |format|
      format.html { redirect_to claims_url, notice: "Claim was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private

    # Use callbacks to share common setup or constraints between actions.
    def set_claim
      @claim = @user.claim.find(params[:id])
    end

    def set_user
      @user = User.find(current_user.id)
    end

    # Only allow a list of trusted parameters through.
    def claim_params
      params.require(:claim).permit(:claimed)
    end
end

app/helpers/claims_helper.rb
module ClaimsHelper
end

app/views/claims/_claim.html.erb
<div id="<%= dom_id claim %>">
  <p>
    <strong>Claimed:</strong>
    <%= claim.claimed %>
  </p>

</div>

app/views/claims/_form.html.erb
<% if claim.errors.any? %>
  <div style="color: red">
    <h2><%= pluralize(claim.errors.count, "error") %> prohibited this claim from being saved:</h2>

    <ul>
      <% claim.errors.each do |error| %>
        <li><%= error.full_message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

<div>
  <%= form.label :claimed, style: "display: block" %>
  <%= form.date_field :claimed %>
</div>

<div>
  <%= form.submit class: 'btn btn-primary' %>
</div>

app/views/claims/edit.html.erb
<h1>Editing claim</h1>
<%= form_with(model: [@claim]) do |form| %>
  <%= render "form", claim: @claim, form: form %>
<% end %>

<br>

<div>
  <%= link_to "Show this claim", @claim %> |
  <%= link_to "Back to claims", user_claims_path(@user) %>
</div>

app/views/claims/index.html.erb
<h1>Claims</h1>

<div id="claims">
  <% @claims.each do |claim| %>
    <%= render claim %>
    <p>
      <%= link_to "Show this claim", claim %>
    </p>
  <% end %>
</div>

app/views/claims/new.html.erb
<h1>New claim</h1>
<%= form_with(model: [@user, @claim]) do |form| %>
  <%= render "form", claim: @claim, form: form %>
<% end %>
<br>

<div>
  <%= link_to "Back to claims", user_claims_path(@user) %>
</div>

app/views/claims/show.html.erb
<%= render @claim %>

<div>
  <%= link_to "Edit this claim", edit_claim_path(@claim) %> |
  <%= link_to "Back to claims", user_claims_path(@user) %>

  <%= button_to "Destroy this claim", @claim, class: 'btn btn-danger', method: :delete %>
</div>