config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resource :user, shallow: true do
    resources :claims
    resources :goals
    resources :tribe_items do
      member do
        get 'individual_item'
      end
    end
    get '/total_tribes', to: 'tribe_items#total_tribes'
  end
  get '/update_alpha', to: 'alpha_coin#update_alpha_coin'

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  # Defines the root path route ("/")
  root "landing#index"
end

app/models/tribe_item.rb
class TribeItem < ApplicationRecord
  belongs_to :user
  validates :owned, presence: true, numericality: { greater_than_or_equal_to: 0 }
end

app/controllers/tribe_items_controller.rb
class TribeItemsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_user
  include Shared
  before_action :set_tribe_item, only: %i[ show edit update destroy ]
  before_action :set_price
  before_action :set_owned
  before_action :daily_yield?
  # GET /tribe_items or /tribe_items.json
  def index
    @akc_price = get_akc_price
    @last_updated = AlphaCoin.first.last_updated.in_time_zone.strftime("%m/%d/%Y %I:%M %p")
    @tribe_items = @user.tribe_items.all.order(:daily_yield)
    @last_claimed = @user.claim.last unless @user.claim.nil?
    @last_claimed_days = to_days(@last_claimed) unless @last_claimed.nil?

  end

  # GET /tribe_items/1 or /tribe_items/1.json
  def show
  end

  # GET /tribe_items/new
  def new
    @tribe_item = @user.tribe_items.build
  end

  # GET /tribe_items/1/edit
  def edit
  end

  # POST /tribe_items or /tribe_items.json
  def create
    @tribe_item = @user.tribe_items.build(tribe_item_params)

    respond_to do |format|
      if @tribe_item.save
        format.html { redirect_to tribe_item_url(@tribe_item), notice: "Tribe item was successfully created." }
        format.json { render :show, status: :created, location: @tribe_item }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @tribe_item.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /tribe_items/1 or /tribe_items/1.json
  def update
    respond_to do |format|
      if @tribe_item.update(tribe_item_params)
        format.html { redirect_to tribe_item_url(@tribe_item), notice: "Tribe item was successfully updated." }
        format.json { render :show, status: :ok, location: @tribe_item }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @tribe_item.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tribe_items/1 or /tribe_items/1.json
  def destroy
    @tribe_item.destroy

    respond_to do |format|
      format.html { redirect_to tribe_items_url, notice: "Tribe item was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  def individual_item
    @item = @user.tribe_items.find(params[:id])
  end

  def total_tribes
    @total_tribes = @owned
  end

  def set_owned
    @owned = get_owned
  end

  private

    def set_user
      @user = User.find(current_user.id)
    end

    # Use callbacks to share common setup or constraints between actions.
    def set_tribe_item
      @tribe_item = @user.tribe_items.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def tribe_item_params
      params.require(:tribe_item).permit(:item, :daily_yield, :price, :owned, :goal)
    end

    def set_price
      price = AlphaCoin.first
      if price.nil?
        update_shared_alpha_coin
      else
        @akc_price = price.price
      end
    end

    def daily_yield?
      @daily_yield = get_sum
    end
end

app/helpers/tribe_items_helper.rb
module TribeItemsHelper
  def convert_to_usd(tribe_price, akc_price)
    number_to_currency(tribe_price * akc_price)
  end

  def convert_to_usd_per_day(days, tribe_price, akc_price)
    day = days * tribe_price
    number_to_currency(day * akc_price)
  end

  def sum_daily_yield(daily_yield, owned)
    no_bonus = number_with_delimiter((daily_yield * owned).round(2))
    bonus = number_with_delimiter(calculate_bonus_tribe(total_daily_yield(daily_yield, owned), @last_claimed_days).round(3))
    [no_bonus, bonus]
  end

  def calculate_bonus_tribe(daily_yield, index)
    daily_yield + (daily_yield * get_bonus(index))
  end

  def calculate_bonus_tribe_split(daily_yield, index)
    bonus = get_bonus(index)
    combined = daily_yield + (daily_yield * bonus)
    [combined, "#{(bonus * 100).round(0)}%", daily_yield]
  end

  def total_daily_yield(daily_yield, owned)
    daily_yield * owned
  end

  private

    def get_bonus(index)
      case index
        when 0..2
          0
        when 3..6
          0.02
        when 5..13
          0.05
        when 14..29
          0.12
        when 30..59
          0.25
        when 60..89
          0.40
        else
          0.50
      end
    end
end

app/views/tribe_items/_form.html.erb
<%= form_with(model: tribe_item) do |form| %>
  <% if tribe_item.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(tribe_item.errors.count, "error") %> prohibited this tribe_item from being saved:</h2>

      <ul>
        <% tribe_item.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :owned, style: "display: block" %>
    <%= form.number_field :owned, min: 0 %>
  </div>

  <div>
    <%= form.submit class: 'btb btn-success' %>
  </div>
<% end %>

app/views/tribe_items/_profit_est.html.erb
<h3>Profit Estimator</h3>

app/views/tribe_items/_table.html.erb
<div class="card-body pt-0">
  <div class="table-responsive">
    <table class="table mb-0 table-striped table-hover">
      <thead>
      <tr>
        <td>Days Owned</td>
        <td>Price in $AKC</td>
        <td>Price in USD</td>
      </tr>
      </thead>
      <tbody>
      <% 1.upto(365) do |index| %>
        <tr>
          <td><%= index %></td>
          <td>
            <% split = calculate_bonus_tribe_split(tot_yield, index) %>
            <%= (index * split[0]).round(1) %>
            <span data-bs-toggle="tooltip" data-bs-placement="top" title="Bonus: <%= split[1] %>">
                        <sup><i class="fa-solid fa-info-circle text-gray-600 "></i></sup>
                      </span>
          </td>
          <td><%= convert_to_usd_per_day(index, tot_yield, @akc_price) %>
        </tr>
      <% end %>

      </tbody>
    </table>
  </div>
</div>

app/views/tribe_items/_tribe_item.html.erb
<div id="<%= dom_id tribe_item %>">
  <p>
    <strong>Item:</strong>
    <%= tribe_item.item %>
  </p>

  <p>
    <strong>Daily yield:</strong>
    <%= tribe_item.daily_yield %>
  </p>

  <p>
    <strong>Price:</strong>
    <%= tribe_item.price %>
  </p>

  <p>
    <strong>Owned:</strong>
    <%= tribe_item.owned %>
  </p>

</div>

app/views/tribe_items/edit.html.erb
<h1>Editing <%= @tribe_item.item %> item</h1>

<%= render "form", tribe_item: @tribe_item %>

<br>

<div>
  <%= link_to "Show this tribe item", @tribe_item %> |
  <%= link_to "Back to tribe items", user_tribe_items_path(@user) %>
</div>

app/views/tribe_items/index.html.erb
<%#= render 'index1' %>
<section>
  <div class="container-fluid">
    <div class="row gy-4">
      <div class="col-md-3 col-sm-6">
        <div class="card mb-0">
          <div class="card-body">
            <div class="d-flex align-items-end justify-content-between mb-2">
              <div class="me-2">
                <i class="fa-solid fa-sack-dollar svg-icon svg-icon-sm svg-icon-heavy text-gray-600 mb-2"></i>
                <p class="text-sm text-uppercase text-gray-600 lh-1 mb-0">Price</p>
              </div>
              <p class="text-xxl lh-1 mb-0 text-dash-color-1">$<%= number_with_delimiter(@akc_price.round(5)) %></p>
            </div>
          </div>
        </div>
      </div>
      <div class="col-md-3 col-sm-6">
        <div class="card mb-0">
          <div class="card-body">
            <div class="d-flex align-items-end justify-content-between mb-2">
              <div class="me-2">
                <i class="fa-solid fa-dollar-sign svg-icon svg-icon-sm svg-icon-heavy text-gray-600 mb-2"></i>
                <i class="fa-solid fa-a svg-icon svg-icon-sm svg-icon-heavy text-gray-600 mb-2"></i>
                <i class="fa-solid fa-k svg-icon svg-icon-sm svg-icon-heavy text-gray-600 mb-2"></i>
                <i class="fa-solid fa-c svg-icon svg-icon-sm svg-icon-heavy text-gray-600 mb-2"></i>
                <p class="text-sm text-uppercase text-gray-600 lh-1 mb-0">Daily Yield</p>
              </div>
              <p class="text-xxl lh-1 mb-0 text-dash-color-2"><%= number_with_delimiter(@daily_yield[0].round(3)) %>
                $AKC</p>
            </div>
          </div>
        </div>
      </div>
      <div class="col-md-3 col-sm-6">
        <div class="card mb-0">
          <div class="card-body">
            <div class="d-flex align-items-end justify-content-between mb-2">
              <div class="me-2">
                <i class="fa-solid fa-money-bill svg-icon svg-icon-sm svg-icon-heavy text-gray-600 mb-2"></i>
                <p class="text-sm text-uppercase text-gray-600 lh-1 mb-0">Price in USD</p>
              </div>
              <p class="text-xxl lh-1 mb-0 text-dash-color-3"><%= number_to_currency(@daily_yield[0] * @akc_price) %></p>
            </div>
          </div>
        </div>
      </div>
      <div class="col-md-3 col-sm-6">
        <div class="card mb-0">
          <div class="card-body">
            <div class="d-flex align-items-end justify-content-between mb-2">
              <div class="me-2">
                <i class="fa-solid fa-clock svg-icon svg-icon-sm svg-icon-heavy text-gray-600 mb-2"></i>
                <p class="text-sm text-uppercase text-gray-600 lh-1 mb-0">Last Updated</p>
              </div>
              <p class="text-md-end lh-1 mb-0 text-dash-color-2"><%= @last_updated %></p>
            </div>
          </div>
        </div>
      </div>
    </div>
    <div class="row gy-4 mt-1">
      <div class="col-md-3 col-sm-6">
        <div class="card mb-0">
          <div class="card-body">
            <div class="d-flex align-items-end justify-content-between mb-2">
              <div class="me-2">
                <i class="fa-solid fa-money-bill svg-icon svg-icon-sm svg-icon-heavy text-gray-600 mb-2"></i>
                <p class="text-sm text-uppercase text-gray-600 lh-1 mb-0">30 Days</p>
              </div>
              <p class="text-xxl lh-1 mb-0 text-dash-color-1">
                <%= number_to_currency(@akc_price * (@daily_yield[0] * 30)) %>
              </p>
            </div>
          </div>
        </div>
      </div>
      <div class="col-md-3 col-sm-6">
        <div class="card mb-0">
          <div class="card-body">
            <div class="d-flex align-items-end justify-content-between mb-2">
              <div class="me-2">
                <i class="fa-solid fa-money-bill-trend-up svg-icon svg-icon-sm svg-icon-heavy text-gray-600 mb-2"></i>
                <i class="fa-solid fa-a svg-icon svg-icon-sm svg-icon-heavy text-gray-600 mb-2"></i>
                <i class="fa-solid fa-k svg-icon svg-icon-sm svg-icon-heavy text-gray-600 mb-2"></i>
                <i class="fa-solid fa-c svg-icon svg-icon-sm svg-icon-heavy text-gray-600 mb-2"></i>
                <p class="text-sm text-uppercase text-gray-600 lh-1 mb-0">60 Days</p>
              </div>
              <p class="text-xxl lh-1 mb-0 text-dash-color-2">
                <%= number_to_currency(@akc_price * @daily_yield[0] * 60) %>
              </p>
            </div>
          </div>
        </div>
      </div>
      <div class="col-md-3 col-sm-6">
        <div class="card mb-0">
          <div class="card-body">
            <div class="d-flex align-items-end justify-content-between mb-2">
              <div class="me-2">
                <i class="fa-solid fa-money-bill-1 svg-icon svg-icon-sm svg-icon-heavy text-gray-600 mb-2"></i>
                <p class="text-sm text-uppercase text-gray-600 lh-1 mb-0">90 Days</p>
              </div>
              <p class="text-xxl lh-1 mb-0 text-dash-color-3">
                <%= number_to_currency(@akc_price * (@daily_yield[0] * 90)) %>

              </p>
            </div>
          </div>
        </div>
      </div>
      <div class="col-md-3 col-sm-6">
        <div class="card mb-0">
          <div class="card-body">
            <div class="d-flex align-items-end justify-content-between mb-2">
              <div class="me-2">
                <i class="fa-solid fa-money-check-dollar svg-icon svg-icon-sm svg-icon-heavy text-gray-600 mb-2"></i>
                <p class="text-sm text-uppercase text-gray-600 lh-1 mb-0">365 Days</p>
              </div>
              <p class="text-xxl lh-1 mb-0 text-dash-color-2">
                <%= number_to_currency(@akc_price * (@daily_yield[0] * 365)) %>
              </p>
            </div>
          </div>
        </div>
      </div>
    </div>
    <div class="row gy-4 mt-1">
      <div class="col-md-3 col-sm-6">
        <div class="card mb-0">
          <div class="card-body">
            <div class="d-flex align-items-end justify-content-between mb-2">
              <div class="me-2">
                <i class="fa-solid fa-calendar-alt svg-icon svg-icon-sm svg-icon-heavy text-gray-600 mb-2"></i>
                <p class="text-sm text-uppercase text-gray-600 lh-1 mb-0">Last Claimed on</p>
              </div>
              <% if @last_claimed.nil? %>
                <%= link_to 'Add Last Claimed', new_user_claim_path(@user, @last_claimed), class: 'badge rounded-pill bg-primary' %>
              <% else %>
                <p class="text-xl lh-1 mb-0 text-dash-color-1">
                  <%= number_with_delimiter(@last_claimed_days) %> days ago
                  (<%= @last_claimed.claimed.strftime('%m/%d/%Y') unless @last_claimed.nil? %>)
                </p>
                <p class="text-xxl-start lh-1 mb-0 text-dash-color-1">

                  <%= link_to 'Edit', edit_claim_path(@last_claimed), class: 'badge rounded-pill bg-primary' %>
                </p>
              <% end %>

            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</section>

<div class="container-fluid">
  <div class="table-responsive">
    <div id="tribe_items">
      <table class="table table-striped">
        <thead>
        <tr>
          <td>Item</td>
          <td>Daily Yield</td>
          <td>Price in $AKC</td>
          <td>Price in USD</td>
          <td>Owned</td>
          <td>Price Spent</td>
        </tr>
        </thead>
        <% @tribe_items.each do |tribe_item| %>
          <tr>
            <td><%= tribe_item.item %></td>
            <% sum = sum_daily_yield(tribe_item.daily_yield, tribe_item.owned) %>
            <td> <%= sum[1] %>
              <% if sum[0].to_f > 0.0 %>
              <span data-bs-toggle="tooltip" data-bs-placement="top" title="Original: <%= sum[0] %>">
                        <sup><i class="fa-solid fa-info-circle text-gray-600 "></i></sup>
                      </span>
              <% end %>
            </td>
            <td><%= tribe_item.price %></td>
            <td><%= number_to_currency(tribe_item.price * @akc_price) %></td>
            <td><%= number_with_delimiter(tribe_item.owned) %></td>
            <td><%= number_to_currency((tribe_item.price * @akc_price) * tribe_item.owned) %></td>
            <td><%= link_to "Edit", edit_tribe_item_path(tribe_item) %></td>
            <td><%= link_to "Show", tribe_item %></td>
          </tr>
        <% end %>
      </table>
    </div>
  </div>
</div>

app/views/tribe_items/individual_item.html.erb
<section class="tables py-0 mt-4">
  <div class="container-fluid">
    <div class="row gy-4">
      <div class="col-lg-6">
        <div class="card mb-0">
          <div class="card-header">
            <h3 class="h4 mb-0"><%= @item.item %> Statistics</h3>
          </div>
          <div class="card-body pt-0">
            <div class="table-responsive">
              <table class="table mb-0">
                <thead>
                <tr>
                  <td>Owned</td>
                  <td>Daily Yield</td>
                  <td>Adj Daily Yield $AKC</td>
                  <td>Price in $AKC</td>
                  <td>Price in USD</td>
                </tr>
                </thead>
                <tbody>
                <tr>
                  <td><%= @item.owned %></td>
                  <td><%= @item.daily_yield %></td>
                  <% tot_yield = total_daily_yield(@item.daily_yield, @item.owned) %>
                  <td><%= tot_yield %></td>
                  <td><%= @item.price %></td>
                  <td><%= convert_to_usd(@item.price, @akc_price) %></td>
                </tr>
                </tbody>
              </table>
            </div>
          </div>
        </div>
      </div>
    </div>
    <div class="row gy-4 mt-3">
      <div class="col-lg-6">
        <div class="card mb-0">
          <div class="card-header">
            <h3 class="h4 mb-0"><%= @item.item %></h3>
          </div>
          <%= render 'tribe_items/table', tot_yield: tot_yield %>
        </div>
      </div>
    </div>
  </div>
</section>

app/views/tribe_items/new.html.erb
<h1>New tribe item</h1>

<%= render "form", tribe_item: @tribe_item %>

<br>

<div>
  <%= link_to "Back to tribe items", user_tribe_items_path(@user) %>
</div>

app/views/tribe_items/show.html.erb
<%= render @tribe_item %>

<div>
  <%= link_to "Edit this tribe item", edit_tribe_item_path(@tribe_item) %> |
  <%= link_to "Back to tribe items", user_tribe_items_path(@user) %>
</div>

app/views/tribe_items/tables.html.erb
<section class="tables py-0 mt-4">
  <div class="container-fluid">
    <div class="row gy-4">
      <div class="col-lg-6">
        <div class="card mb-0">
          <div class="card-header">
            <h3 class="h4 mb-0"><%= @item.item %> Statistics</h3>
          </div>
          <div class="card-body pt-0">
            <div class="table-responsive">
              <table class="table mb-0">
                <thead>
                <tr>
                  <td>Owned</td>
                  <td>Daily Yield</td>
                  <td>Adj Daily Yield $AKC</td>
                  <td>Price in $AKC</td>
                  <td>Price in USD</td>
                </tr>
                </thead>
                <tbody>
                <tr>
                  <td><%= @item.owned %></td>
                  <td><%= @item.daily_yield %></td>
                  <td><%= @item.daily_yield * @item.owned %></td>
                  <td><%= @item.price %></td>
                  <td><%= convert_to_usd(@item.price, @akc_price) %></td>
                </tr>
                </tbody>
              </table>
            </div>
          </div>
        </div>
      </div>
    </div>
    <div class="row gy-4 mt-3">
      <div class="col-lg-6">
        <div class="card mb-0">
          <div class="card-header">
            <h3 class="h4 mb-0"><%= @item.item %></h3>
          </div>
          <div class="card-body pt-0">
            <div class="table-responsive">
              <table class="table mb-0 table-striped table-hover">
                <thead>
                <tr>
                  <td>Days Owned</td>
                  <td>Price in $AKC</td>
                  <td>Price in USD</td>
                </tr>
                </thead>
                <tbody>
                <% 1.upto(365) do |index| %>
                  <tr>
                    <td><%= index %></td>
                    <td><%= (index * (@item.daily_yield * @item.owned)).round(1) %></td>
                    <td><%= convert_to_usd_per_day(index, (@item.daily_yield * @item.owned), @akc_price) %></td>
                  </tr>
                <% end %>

                </tbody>
              </table>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</section>

app/views/tribe_items/total_tribes.html.erb
<section class="tables py-0 mt-4">
  <div class="container-fluid">
    <div class="row gy-4">
      <div class="col-lg-6">
        <div class="card mb-0">
          <div class="card-header">
            <h3 class="h4 mb-0">Total Tribe Statistics</h3>
          </div>
          <div class="card-body pt-0">
            <div class="table-responsive">
              <table class="table mb-0">
                <thead>
                <tr>
                  <td>Tribe</td>
                  <td>Owned</td>
                  <td>Daily Yield</td>
                  <td>Adj Daily Yield $AKC</td>
                  <td>Price in $AKC</td>
                  <td>Price in USD</td>
                </tr>
                </thead>
                <tbody>
                <% tot_yield = 0 %>

                <% @total_tribes.each do |item| %>
                  <% yield_per_item = total_daily_yield(item.daily_yield, item.owned) %>
                  <tr>
                    <td><%= item.item %></td>
                    <td><%= item.owned %></td>
                    <td><%= item.daily_yield %></td>
                    <td><%= yield_per_item %></td>
                    <td><%= item.price %></td>
                    <td><%= convert_to_usd(item.price, @akc_price) %></td>
                  </tr>
                  <% tot_yield += yield_per_item %>
                <% end %>
                </tbody>
              </table>
              <strong class="mt-1">Daily yield: <%= tot_yield %></strong>
            </div>
          </div>
        </div>
      </div>
    </div>
    <div class="row gy-4 mt-3">
      <div class="col-lg-6">
        <div class="card mb-0">
          <div class="card-header">
            <h3 class="h4 mb-0">Total</h3>
          </div>
          <%= render 'tribe_items/table', tot_yield: tot_yield %>
        </div>
      </div>
    </div>
  </div>
</section>