config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resource :user, shallow: true do
    resources :claims
    resources :goals
    resources :tribe_items do
      member do
        get 'individual_item'
      end
    end
    get '/total_tribes', to: 'tribe_items#total_tribes'
  end
  get '/update_alpha', to: 'alpha_coin#update_alpha_coin'

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  # Defines the root path route ("/")
  root "landing#index"
end

app/models/goal.rb
class Goal < ApplicationRecord
  belongs_to :user
end

app/controllers/goals_controller.rb
class GoalsController < ApplicationController
	before_action :authenticate_user!
	before_action :set_user
	include Shared
	before_action :set_goal, only: %i[ show edit update destroy ]
	before_action :set_owned
	before_action :set_last_claimed
	before_action :daily_yield?
	before_action :akc_price?
	before_action :split_daily_yield?
	# GET /goals or /goals.json
	def index
		@goals = @user.goals
	end

	# GET /goals/1 or /goals/1.json
	def show
		id = @user.goals.find(params[:id])
		@set_goal = id.goal
		@akc_price = akc_price?
		@num_days_to_collect = id.num_days_to_collect
		@first_day_to_collect = id.first_day_to_collect
		@unclaimed_coins = id.unclaimed_coins
		@num_days = (Time.now.to_date - @user.goals.last.started_on.to_date).to_i
		@errors = Set.new
		buy_tribes = all_tribes(@unclaimed_coins, @set_goal)
		lab_and_higher = lab_plus(@unclaimed_coins, @set_goal)
		starship_and_higher = starship_plus(@unclaimed_coins, @set_goal)
		city_and_higher = city_plus(@unclaimed_coins, @set_goal)
		only_arenaa = only_arena(@unclaimed_coins, @set_goal)
		no_tribes = no_tribes(@unclaimed_coins, @set_goal)
		only_mini_starship = only_mini_starship(@unclaimed_coins, @set_goal)
		only_mini_lab = only_mini_lab(@unclaimed_coins, @set_goal)

		@show = {}

		@show[:all_tribes] = buy_tribes unless buy_tribes.nil?
		@show[:lab_plus] = lab_and_higher unless lab_and_higher.nil?
		@show[:starship_plus] = starship_and_higher unless starship_and_higher.nil?
		@show[:city_plus] = city_and_higher unless city_and_higher.nil?
		@show[:only_arena] = only_arenaa unless only_arenaa.nil?
		@show[:only_mini_lab] = only_mini_lab unless only_mini_lab.nil?
		@show[:only_mini_starship] = only_mini_starship unless only_mini_starship.nil?
		@show[:no_tribes] = no_tribes unless no_tribes.nil?
		@show = @show.sort_by { |k, v| v[0] }

		if @errors.present?
			string = ''
			@errors.each do |k|
				string += "#{k}"
			end
			redirect_to user_goals_path(@user), alert: string
		end
		# @only_mini_lab = nil
		# @buy_tribes = nil
		# @only_mini_starship = nil
		# @no_tribes = nil

	end

	# GET /goals/new
	def new
		@goal = @user.goals.build
	end

	# GET /goals/1/edit
	def edit
	end

	# POST /goals or /goals.json
	def create
		@last_claimed = Claim.last.claimed.strftime("%d/%m/%Y")
		@goal = @user.goals.build(goal_params)

		respond_to do |format|
			if @goal.save
				format.html { redirect_to goal_url(@goal), notice: "Goal was successfully created." }
				format.json { render :show, status: :created, location: @goal }
			else
				format.html { render :new, status: :unprocessable_entity }
				format.json { render json: @goal.errors, status: :unprocessable_entity }
			end
		end
	end

	# PATCH/PUT /goals/1 or /goals/1.json
	def update
		respond_to do |format|
			if @goal.update(goal_params)
				format.html { redirect_to goal_url(@goal), notice: "Goal was successfully updated." }
				format.json { render :show, status: :ok, location: @goal }
			else
				format.html { render :edit, status: :unprocessable_entity }
				format.json { render json: @goal.errors, status: :unprocessable_entity }
			end
		end
	end

	# DELETE /goals/1 or /goals/1.json
	def destroy
		@goal.destroy

		respond_to do |format|
			format.html { redirect_to user_goals_path(@user), notice: "Goal was successfully destroyed." }
			format.json { head :no_content }
		end
	end

	def set_owned
		@owned = get_owned
	end

	private

		# Use callbacks to share common setup or constraints between actions.
		def set_goal
			@goal = @user.goals.find(params[:id])
		end

		def set_last_claimed
			claimed = @user.claim.last
			date = if claimed.nil?
				       Time.now.strftime("%Y-%m-%d")
				     else
					     claimed.claimed.strftime("%Y-%m-%d")
			       end
			@last_claimed = date
		end

		def set_user
			@user = User.find(current_user.id)
		end

		# Only allow a list of trusted parameters through.
		def goal_params
			params.require(:goal).permit(:unclaimed_coins, :goal, :started_on, :num_days_to_collect, :first_day_to_collect)
		end

		LAB_PRICE = 100
		STARSHIP_PRICE = 200
		CITY_PRICE = 200
		ARENA_PRICE = 800
		MINI_LAB_PRICE = 10
		MINI_STAR_SHIP_PRICE = 50

		def get_prices(total)
			if total >= 2
				{
					lab_price: calculate_discount(LAB_PRICE, total),
					starship_price: calculate_discount(STARSHIP_PRICE, total),
					city_price: calculate_discount(CITY_PRICE, total),
					arena_price: calculate_discount(ARENA_PRICE, total),
					mini_lab_price: calculate_discount(MINI_LAB_PRICE, total),
					min_star_ship_price: calculate_discount(MINI_STAR_SHIP_PRICE, total)
				}
			else
				{
					lab_price: 100,
					starship_price: 200,
					city_price: 400,
					arena_price: 800,
					mini_lab_price: 10,
					min_star_ship_price: 50
				}
			end

		end

		def no_tribes(unclaimed_coins, goal)
			sum = unclaimed_coins
			daily_yield = get_sum[0]
			return @errors << "Please add Tribe Items before continuing" if daily_yield === 0
			no_tribes_arr = []
			index = 0
			while goal >= sum
				sum += daily_yield
				if goal < sum
					no_tribes_arr << {
						days: index,
						on: Time.now + index.days,
						bought: 0,
						item: nil,
						sum: sum,
						daily_yield: calculate_bonus_goal(daily_yield, index)
					}
					return [index, daily_yield, sum, no_tribes_arr]
				end
				if @num_days_to_collect.nonzero?
					days = Date.today.next_day(index)
					if days >= @first_day_to_collect
						unless index % @num_days_to_collect === 0
							index += 1
							next
						end
					else
						index += 1
						next
					end
				end
				# puts "last index: #{index}"
				no_tribes_arr << {
					days: index,
					on: Time.now + index.days,
					bought: 0,
					item: nil,
					sum: sum,
					daily_yield: calculate_bonus_goal(daily_yield, index)
				}
				# raise "goal: #{no_tribes_arr}"
				# puts "no_tribes_arr: #{no_tribes_arr}"
				index += 1
			end
			[index, daily_yield, sum, no_tribes_arr]
		end

		def only_mini_starship(unclaimed_coins, goal)
			sum = unclaimed_coins
			daily_yield = get_sum[0]
			total_mini_starships = 0
			return @errors << "Please add Tribe Items before continuing" if daily_yield === 0
			only_mini_starship_arr = []
			total = 0
			days = 0
			max_days = 1
			index = 0
			while goal > sum
				# days += 1
				sum += daily_yield
				if goal < sum
					only_mini_starship_arr << {
						days: index,
						on: Time.now + index.days,
						bought: 0,
						item: 'Mini Starship',
						sum: sum,
						daily_yield: daily_yield
					}
					return [index, daily_yield, sum, only_mini_starship_arr]
				end
				# puts "days: #{days}"
				if @num_days_to_collect.nonzero?
					days = Date.today.next_day(index)
					if days >= @first_day_to_collect
						unless index % @num_days_to_collect === 0
							index += 1
							next
						end
					else
						index += 1
						next
					end
				end
				prices = get_prices(index)

				count = 0
				# puts "total: #{total}. min_star_ship_price: #{prices[:min_star_ship_price]}"
				# return [index, daily_yield, sum] if (goal < sum) || (index >= days)
				if goal < sum
					only_mini_starship_arr << {
						days: index,
						on: Time.now + index.days,
						bought: count,
						item: 'Mini Starship',
						sum: sum,
						daily_yield: daily_yield
					}
					return [index, daily_yield, sum, only_mini_starship_arr]
				end
				# raise "#{sum } > #{prices[:min_star_ship_price]}"
				while sum > prices[:min_star_ship_price]
					sum -= prices[:min_star_ship_price]
					daily_yield += calculate_bonus_goal(1, index)
					count += 1
					# puts "#{index} Bought mini starship on #{Time.now + index.days}. Sum: #{sum}. Daily yield: #{daily_yield}"
				end
				next if count === 0
				total_mini_starships += count
				total += count
				only_mini_starship_arr << {
					days: index,
					on: Time.now + index.days,
					bought: count,
					item: 'Mini Starship',
					sum: sum,
					daily_yield: daily_yield
				}
				index += 1
				# puts "Total: #{total_mini_starships}. Bought #{count} mini starships on #{Time.now + index.days}. Sum: #{sum}. Daily yield: #{daily_yield}"
			end
			[index, daily_yield, sum, only_mini_starship_arr]
		end

		def only_mini_lab(unclaimed_coins, goal)
			sum = unclaimed_coins
			daily_yield = get_sum[0]
			total_mini_lab = 0
			return @errors << "Please add Tribe Items before continuing" if daily_yield === 0
			only_mini_lab_arr = []
			total = 0
			days = 0
			max_days = 14
			index = 0
			while goal > sum
				sum += daily_yield
				if goal < sum
					only_mini_lab_arr << {
						days: index,
						on: Time.now + index.days,
						bought: 0,
						item: 'Mini Lab',
						sum: sum,
						daily_yield: daily_yield
					}
					return [index, daily_yield, sum, only_mini_lab_arr]
				end
				if @num_days_to_collect.nonzero?
					days = Date.today.next_day(index)
					if days >= @first_day_to_collect
						unless index % @num_days_to_collect === 0
							index += 1
							next
						end
					else
						index += 1
						next
					end
				end

				# puts "days: #{days}"
				prices = get_prices(index)

				count = 0
				# puts "total: #{total}. min_star_lab_price: #{prices[:min_star_ship_price]}"
				# return [index, daily_yield, sum] if (goal < sum) || (index >= days)
				if goal < sum
					only_mini_lab_arr << {
						days: index,
						on: Time.now + index.days,
						bought: count,
						item: 'Mini Lab',
						sum: sum,
						daily_yield: daily_yield
					}
					return [index, daily_yield, sum, only_mini_lab_arr]
				end
				while sum > prices[:mini_lab_price]
					sum -= prices[:mini_lab_price]
					daily_yield += calculate_bonus_goal(0.15, index)
					count += 1
					# puts "#{index} Bought mini starship on #{Time.now + index.days}. Sum: #{sum}. Daily yield: #{daily_yield}"
				end
				next if count === 0
				total_mini_lab += count
				total += count
				only_mini_lab_arr << {
					days: index,
					on: Time.now + index.days,
					bought: count,
					item: 'Lab',
					sum: sum,
					daily_yield: daily_yield
				}
				index += 1

app/helpers/goals_helper.rb
module GoalsHelper
  def akc_price
    AlphaCoin.first.price
  end

  def format_date(num_days)
    (Time.now + num_days.days).strftime('%m/%d/%Y')
  end

  def convert_to_usd(coin)
    coin * akc_price
  end
end

app/views/goals/_form.html.erb
<% if goal.errors.any? %>
  <div style="color: red">
    <h2><%= pluralize(goal.errors.count, "error") %> prohibited this goal from being saved:</h2>

    <ul>
      <% goal.errors.each do |error| %>
        <li><%= error.full_message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

<div class="form-floating mb-3">
  <%= form.number_field :unclaimed_coins, class: 'form-control', id: 'unclaimed_coins', placeholder: 0, step: :any %>
  <%= form.label :unclaimed_coins, for: 'unclaimed_coins' %>
</div>

<div class="form-floating mb-3">
  <%= form.number_field :goal, class: 'form-control', id: 'goal', placeholder: 0, step: :any %>
  <%= form.label :goal, for: 'goal' %>
</div>

<div class="form-floating mb-3">
  <%= form.date_field :started_on, class: 'form-control', id: 'started_on', placeholder: 'MM/DD/YYYY', value: @last_claimed %>
  <%= form.label :started_on, for: 'started_on' %>
</div>

<div class="form-floating mb-3">
  <%= form.number_field :num_days_to_collect, class: 'form-control', id: 'num_days_to_collect' %>
  <%= form.label :num_days_to_collect, for: 'num_days_to_collect' %>
</div>

<div class="form-floating mb-3">
  <%= form.date_field :first_day_to_collect, class: 'form-control', id: 'first_day_to_collect', placeholder: 'MM/DD/YYYY' %>
  <%= form.label :first_day_to_collect, for: 'first_day_to_collect' %>
</div>

<div>
  <%= form.submit class: 'btn btn-success' %>
</div>

app/views/goals/_goal.html.erb
<div id="<%= dom_id goal %>">
  <tr>
    <td><%= goal.unclaimed_coins %></td>
    <td><%= goal.goal %></td>
    <td><%= goal.started_on %></td>
    <td><%= goal.num_days_to_collect %></td>
    <td><%= link_to "Edit", edit_goal_path(goal) %></td>
    <td><%= link_to "Show", goal %></td>
  </tr>
</div>

app/views/goals/_items.html.erb
<div class="table-responsive">
  <div id="goal_items">
    <table class="table table-striped">
      <thead>
      <tr>
        <td>Days</td>
        <td>Bought On</td>
        <td>Bought</td>
        <td>$AKC</td>
        <td>Daily Yield</td>
        <td>Daily Yield USD</td>
        <td>7 days</td>
        <td>14 days</td>
        <td>30 days</td>
        <td>60 days</td>
        <td>90 days</td>
        <td>365 days</td>
      </tr>
      </thead>
      <%#= raise "items: #{items}" %>
      <%= raise "Items is nil. #{items}" if items.nil? %>
      <% items.each do |item| %>
        <tr class="text-end">
          <td><%= number_with_delimiter(item[:days]) %></td>
          <td><%= item[:on].strftime('%m/%d/%Y') unless item[:on].nil? %></td>
          <td><%= pluralize(number_with_delimiter(item[:bought]), item[:item]) unless item[:item].nil? %></td>
          <td><%= number_with_delimiter(item[:sum].round(3)) unless item[:sum].nil? %></td>
          <% dy = item[:daily_yield].round(3) %>
          <td><%= number_with_delimiter(dy) %></td>
          <td><%= number_to_currency(@akc_price * dy) %></td>
          <td>
            <%= number_to_currency(@akc_price * (dy * 7)) %>
            <span data-bs-toggle="tooltip" data-bs-placement="top" title="7 days from bought: <%= (item[:on] + 7.days).strftime("%m/%d/%Y") %>">
              <sup><i class="fa-solid fa-info-circle text-gray-600 "></i></sup>
            </span>
          </td>
          <td>
            <%= number_to_currency(@akc_price * (dy * 14)) %>
            <span data-bs-toggle="tooltip" data-bs-placement="top" title="7 days from bought: <%= (item[:on] + 14.days).strftime("%m/%d/%Y") %>">
              <sup><i class="fa-solid fa-info-circle text-gray-600 "></i></sup>
            </span>
          </td>
          <td>
            <%= number_to_currency(@akc_price * (dy * 30)) %>
            <span data-bs-toggle="tooltip" data-bs-placement="top" title="30 days from bought: <%= (item[:on] + 30.days).strftime("%m/%d/%Y") %>">
              <sup><i class="fa-solid fa-info-circle text-gray-600 "></i></sup>
            </span>
          </td>
          <td>
            <%= number_to_currency(@akc_price * (dy * 60)) %>
            <span data-bs-toggle="tooltip" data-bs-placement="top" title="60 days from bought: <%= (item[:on] + 60.days).strftime("%m/%d/%Y") %>">
              <sup><i class="fa-solid fa-info-circle text-gray-600 "></i></sup>
            </span>
          </td>
          <td>
            <%= number_to_currency(@akc_price * (dy * 90)) %>
            <span data-bs-toggle="tooltip" data-bs-placement="top" title="90 days from bought: <%= (item[:on] + 90.days).strftime("%m/%d/%Y") %>">
              <sup><i class="fa-solid fa-info-circle text-gray-600 "></i></sup>
            </span>
          </td>
          <td>
            <%= number_to_currency(@akc_price * (dy * 365)) %>
            <span data-bs-toggle="tooltip" data-bs-placement="top" title="365 days from bought: <%= (item[:on] + 365.days).strftime("%m/%d/%Y") %>">
              <sup><i class="fa-solid fa-info-circle text-gray-600 "></i></sup>
            </span>
          </td>
        </tr>
      <% end %>
    </table>
  </div>
</div>

app/views/goals/edit.html.erb
<h1>Editing goal</h1>

<%= form_with(model: [@goal]) do |form| %>
  <%= render "form", goal: @goal, form: form %>
<% end %>

<br>

<div>
  <%= link_to "Show this goal", @goal %> |
  <%= link_to "Back to goals", user_goals_path(@user) %>
</div>

app/views/goals/index.html.erb
<h1>Goals</h1>
<% unless @goals.empty? %>
  <div id="goals">
    <table class="table table-striped">
      <thead>
      <tr>
        <td>Unclaimed Coins</td>
        <td>Goal</td>
        <td>Started On</td>
        <td>Num days to collect</td>

      </tr>
      </thead>
      <% @goals.each do |goal| %>
        <%= render goal %>
      <% end %>
    </table>
  </div>
<% end %>
<%= link_to "New goal", new_user_goal_path(@user) %>

app/views/goals/new.html.erb
<h1>New goal</h1>

<%= form_with(model: [@user, @goal]) do |form| %>
  <%= render "form", goal: @goal, form: form %>
<% end %>

<br>

<div>
  <%= link_to "Back to goals", user_goals_path(@user) %>
</div>

app/views/goals/show.html.erb
<div class="container-fluid">
  <div class="row gy-4">
    <div class="row gy-4">
      <div class="col-md-3 col-sm-6">
        <div class="card mb-0">
          <div class="card-body">
            <div class="d-flex align-items-end justify-content-between mb-2">
              <div class="me-2">
                <i class="fa-solid fa-info-circle svg-icon svg-icon-sm svg-icon-heavy text-gray-600 mb-2"></i>
                <p class="text-sm text-uppercase text-gray-600 lh-1 mb-0">Info</p>
              </div>
              <%= link_to "Back to goals", user_goals_path(@user), class: 'badge rounded-pill bg-success' %>
              <%= link_to "Edit Goal", edit_goal_path(@goal), class: 'badge rounded-pill bg-info' %>
              <%= button_to "Destroy this goal", @goal, class: 'badge rounded-pill bg-danger', method: :delete %>
            </div>
          </div>
        </div>
      </div>
      <div class="col-md-3 col-sm-6">
        <div class="card mb-0">
          <div class="card-body">
            <div class="d-flex align-items-end justify-content-between mb-2">
              <div class="me-2">
                <i class="fa-solid fa-coins svg-icon svg-icon-sm svg-icon-heavy text-gray-600 mb-2"></i>
                <p class="text-sm text-uppercase text-gray-600 lh-1 mb-0">Unclaimed Coins</p>
              </div>
              <p class="text-xxl lh-1 mb-0 text-dash-color-1"><%= number_with_delimiter(@unclaimed_coins) %></p>
            </div>
          </div>
        </div>
      </div>
      <div class="col-md-3 col-sm-6">
        <div class="card mb-0">
          <div class="card-body">
            <div class="d-flex align-items-end justify-content-between mb-2">
              <div class="me-2">
                <i class="fa-solid fa-calendar-day svg-icon svg-icon-sm svg-icon-heavy text-gray-600 mb-2"></i>
                <p class="text-sm text-uppercase text-gray-600 lh-1 mb-0">Number of days to collect</p>
              </div>
              <p class="text-xxl lh-1 mb-0 text-dash-color-1"><%= number_with_delimiter(@num_days_to_collect) %></p>
            </div>
          </div>
        </div>
      </div>
      <div class="col-md-3 col-sm-6">
        <div class="card mb-0">
          <div class="card-body">
            <div class="d-flex align-items-end justify-content-between mb-2">
              <div class="me-2">
                <i class="fa-solid fa-calendar-day svg-icon svg-icon-sm svg-icon-heavy text-gray-600 mb-2"></i>
                <p class="text-sm text-uppercase text-gray-600 lh-1 mb-0">First day to collect</p>
              </div>
              <p class="text-xxl lh-1 mb-0 text-dash-color-1"><%= number_with_delimiter(@first_day_to_collect.strftime('%m/%d/%Y')) %></p>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
  <div class="row">
    <div class="row gy-2">
      <div class="col-md-3 col-sm-6">
        <div class="card mb-0">
          <div class="card-body">
            <div class="d-flex align-items-end justify-content-between mb-2">
              <div class="me-2">
                <i class="fa-solid fa-sack-dollar svg-icon svg-icon-sm svg-icon-heavy text-gray-600 mb-2"></i>
                <p class="text-sm text-uppercase text-gray-600 lh-1 mb-0">Price</p>
              </div>
              <p class="text-xxl lh-1 mb-0 text-dash-color-1">$<%= number_with_delimiter(@akc_price.round(5)) %></p>
            </div>
          </div>
        </div>
      </div>
      <div class="col-md-3 col-sm-6">
        <div class="card mb-0">
          <div class="card-body">
            <div class="d-flex align-items-end justify-content-between mb-2">
              <div class="me-2">
                <i class="fa-solid fa-dollar-sign svg-icon svg-icon-sm svg-icon-heavy text-gray-600 mb-2"></i>
                <i class="fa-solid fa-a svg-icon svg-icon-sm svg-icon-heavy text-gray-600 mb-2"></i>
                <i class="fa-solid fa-k svg-icon svg-icon-sm svg-icon-heavy text-gray-600 mb-2"></i>
                <i class="fa-solid fa-c svg-icon svg-icon-sm svg-icon-heavy text-gray-600 mb-2"></i>
                <p class="text-sm text-uppercase text-gray-600 lh-1 mb-0">Daily Yield</p>
              </div>
              <p class="text-xxl lh-1 mb-0 text-dash-color-2"><%= number_with_delimiter(@daily_yield[0].round(3)) %>
                $AKC</p>
            </div>
          </div>
        </div>
      </div>
      <div class="col-md-3 col-sm-6">
        <div class="card mb-0">
          <div class="card-body">
            <div class="d-flex align-items-end justify-content-between mb-2">
              <div class="me-2">
                <i class="fa-solid fa-medal svg-icon svg-icon-sm svg-icon-heavy text-gray-600 mb-2"></i>
                <p class="text-sm text-uppercase text-gray-600 lh-1 mb-0">Goal</p>
              </div>
              <p class="text-xxl lh-1 mb-0 text-dash-color-3"><%= number_with_delimiter(@set_goal) %></p>
            </div>
          </div>
        </div>
      </div>
      <div class="col-md-3 col-sm-6">
        <div class="card mb-0">
          <div class="card-body">
            <div class="d-flex align-items-end justify-content-between mb-2">
              <div class="me-2">
                <i class="fa-solid fa-clock svg-icon svg-icon-sm svg-icon-heavy text-gray-600 mb-2"></i>
                <p class="text-sm text-uppercase text-gray-600 lh-1 mb-0">Days Since Claimed</p>
              </div>
              <p class="text-xxl lh-1 mb-0 text-dash-color-2"><%= number_with_delimiter(@num_days) %></p>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>

  <div class="row gy-4">
    <div class="row gy-4">
      <% @show.each do |k, v| %>
        <% next if v.nil? %>
        <div class="col-md-3 col-sm-6">
          <div class="card mb-3">
            <div class="card-body">
              <div class="d-flex align-items-end justify-content-between mb-2">
                <div class="me-2">
                  <i class="fa-solid fa-warehouse svg-icon svg-icon-sm svg-icon-heavy text-gray-600 mb-2"></i>
                  <p class="text-sm text-uppercase text-gray-600 lh-1 mb-0"><%= k.to_s.humanize %></p>
                </div>
                <div class="text-xxs lh-1 mb-0 text-dash-color-1">
                <span class="badge rounded-pill bg-primary m-1">
                  <%= number_with_delimiter(v[0]) %> days
                  <span data-bs-toggle="tooltip" data-bs-placement="top" title="<%= distance_of_time_in_words(0, v[0].days) %>">
                    <sup><i class="fa-solid fa-info-circle text-gray-600 "></i></sup>
                  </span>
                </span>
                  <span class="badge rounded-pill bg-danger">Date: <%= format_date(v[0]) unless v.nil? %></span>
                  <span class="badge rounded-pill bg-secondary m-1">Daily Yield: <%= number_with_delimiter(v[1].round(2)) unless v.nil? %></span>
                  <span class="badge rounded-pill bg-success m-1">DY: <%= convert_to_usd(v[1], @akc_price) unless v.nil? %></span>
                  <span class="badge rounded-pill bg-warning text-dark m-1">Leftover: <%= convert_to_usd(v[2].round(2), @akc_price) unless v.nil? %></span>
                  <span class="badge rounded-pill bg-info text-dark m-1"><%= number_with_delimiter(v[2].round(2)) unless v.nil? %>
                    $AKC</span>
                </div>
              </div>
            </div>
          </div>
        </div>
      <% end %>
    </div>
  </div>
  <div class="mt-3">
    <div class="accordion" id="accordionExample">
      <% @show.each.with_index do |(k, v), index| %>
        <% next if v.nil? %>
        <div class="accordion-item">
          <h2 class="accordion-header" id="heading-<%= index %>">
            <button class="accordion-button collapsed" type="button" data-bs-toggle="collapse" data-bs-target="#collapse-<%= index %>" aria-expanded="false" aria-controls="collapse-<%= index %>">
              <%= k.to_s.titleize %>
            </button>
          </h2>
          <div id="collapse-<%= index %>" class="accordion-collapse collapse" aria-labelledby="heading-<%= index %>" data-bs-parent="#accordionExample">
            <div class="accordion-body">
              <%= render 'goals/items', items: v[3] unless v.nil? %>
            </div>
          </div>
        </div>
      <% end %>
    </div>
  </div>
</div>