config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resource :user, shallow: true do
    resources :claims
    resources :goals
    resources :tribe_items do
      member do
        get 'individual_item'
      end
    end
    get '/total_tribes', to: 'tribe_items#total_tribes'
  end
  get '/update_alpha', to: 'alpha_coin#update_alpha_coin'

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  # Defines the root path route ("/")
  root "landing#index"
end

app/views/layouts/_footer.html.erb
<!-- Page Footer-->
<footer class="position-absolute bottom-0 bg-dash-dark-2 text-white text-center py-3 w-100 text-xs" id="footer">
  <div class="container-fluid text-center">
    <!-- Please do not remove the backlink to us unless you support us at https://bootstrapious.com/donate. It is part of the license conditions. Thank you for understanding :)-->
    <p class="mb-0 text-dash-gray"><%= Time.now.strftime("%Y") %> &copy; KongCal. Design by
      <a href="https://bootstrapious.com">Bootstrapious</a>.</p>
  </div>
</footer>

app/views/layouts/_header.html.erb
<header class="header">
  <nav class="navbar navbar-expand-lg py-3 bg-dash-dark-2 border-bottom border-dash-dark-1 z-index-10">
    <div class="container-fluid d-flex align-items-center justify-content-between py-1">
      <div class="navbar-header d-flex align-items-center">
        <%= link_to root_path, class: 'navbar-brand text-uppercase text-reset' do %>
          <div class="brand-text brand-big"><strong class="text-primary">Kong</strong><strong>Cal</strong></div>
          <div class="brand-text brand-sm"><strong class="text-primary">K</strong><strong>C</strong></div>
        <% end %>
        <% unless controller_name === 'landing' %>
          <button class="sidebar-toggle">
            <i class="fa-solid fa-arrow-left"></i>
          </button>
        <% end %>
      </div>
      <ul class="list-inline mb-0">
        <% if user_signed_in? %>
          <li class="list-inline-item edit px-lg-2">
            <%= link_to edit_user_registration_path class: 'nav-link' do %>
            <span class="">
             <i class="fa-solid fa-edit"></i> Edit Profile
            </span>
              </li>
            <% end %>
            <li class="list-inline-item logout px-lg-2">
              <%= button_to destroy_user_session_path, method: :delete, class: 'nav-link btn btn-primary', data: { turbo: false } do %>
            <span class="">
             <i class="fa-solid fa-sign-out"></i> Logout
            </span>
              <% end %>
            </li>
        <% else %>
          <li class="list-inline-item logout px-lg-2">
            <%= link_to new_user_registration_path, class: 'nav-link text-sm text-reset px-1 px-lg-0' do %>
            <span class="d-none d-sm-inline-block">
             <i class="fa-solid fa-user-plus svg-icon svg-icon-sm svg-icon-heavy text-gray-600"></i> Sign Up
            </span>
            <% end %>
          </li>
          <li class="list-inline-item logout px-lg-2">
            <%= link_to new_user_session_path, class: 'nav-link text-sm text-reset px-1 px-lg-0' do %>
            <span class="d-none d-sm-inline-block">
             <i class="fa-solid fa-sign-in-alt svg-icon svg-icon-sm svg-icon-heavy text-gray-600"></i> Login
            </span>
            <% end %>
          </li>
        <% end %>
      </ul>
    </div>
  </nav>
</header>

app/views/layouts/_notices.html.erb
<% if notice %>
  <div class="alert alert-primary alert-dismissible bg-primary text-white border-0 fade show" role="alert">
    <%= notice %>
    <button type="button" class="btn-close btn-close-white" data-bs-dismiss="alert" aria-label="Close"></button>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-danger alert-dismissible bg-danger text-white border-0 fade show" role="alert">
    <button type="button" class="btn-close btn-close-white" data-bs-dismiss="alert" aria-label="Close"></button>
    <%= content_tag :div, alert.html_safe %>
    <%#= alert %>
  </div>
<% end %>

app/views/layouts/_sidebar.html.erb
<!-- Sidebar Navigation-->
<nav id="sidebar">
  <!-- Sidebar Header-->
  <div class="sidebar-header d-flex align-items-center p-4">
    <!--    <img class="avatar shadow-0 img-fluid rounded-circle" src="https://loremflickr.com/320/240?random=1" alt="...">-->
    <!--    <div class="ms-3 title">-->
    <!--      <h1 class="h5 mb-1">Mark Stephen</h1>-->
    <!--      <p class="text-sm text-gray-700 mb-0 lh-1">Web Designer</p>-->
    <!--    </div>-->
  </div>

  <span class="text-uppercase text-gray-600 text-xs mx-3 px-2 heading mb-2">$AKC</span>
  <ul class="list-unstyled">
    <li class="sidebar-item">
      <%= link_to url_for(action: 'update_alpha_coin', controller: 'alpha_coin'), remote: true,
                  class: 'sidebar-link' do %>
        <i class="fa-solid fa-coins svg-icon svg-icon-sm svg-icon-heavy"></i> <span> Update $AKC</span>
      <% end %>
    </li>
  </ul>
  <span class="text-uppercase text-gray-600 text-xs mx-3 px-2 heading mb-2">Main</span>
  <ul class="list-unstyled">
    <li class="sidebar-item active">
      <%= link_to user_tribe_items_path(@user), class: 'sidebar-link' do %>
        <i class="fa-solid fa-house svg-icon svg-icon-sm svg-icon-heavy"></i> <span> Home</span>
      <% end %>
    </li>
    <% unless @owned.blank? %>
      <li class="sidebar-item"><a class="sidebar-link" href="#exampledropdownDropdown" data-bs-toggle="collapse">
        <i class="fa-solid fa-chart-line svg-icon svg-icon-sm svg-icon-heavy"></i>
        <span>Tables</span></a>
        <ul class="collapse list-unstyled " id="exampledropdownDropdown">
          <li><%= link_to 'All Tribe Items', total_tribes_user_path(@user), class: 'sidebar-link' %></li>
          <% @owned.each do |ti| %>
            <li><%= link_to ti.item, individual_item_tribe_item_path(ti.id), class: 'sidebar-link' %></li>
          <% end %>
        </ul>
      </li>
      <li class="sidebar-item">
        <%= link_to user_goals_path(@user), class: 'sidebar-link' do %>
          <i class="fa-solid fa-calendar-days svg-icon svg-icon-sm svg-icon-heavy"></i>
          <span>  Goal</span>
        <% end %>
      </li>
    <% end %>
  </ul>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
  <title>KongCal - Alpha Kong Club Profit Estimator</title>
  <meta name="description" content="Alpha Kong Club Profit Estimator">
  <meta name="viewport" content="width=device-width,initial-scale=1">
  <meta name="robots" content="all,follow">
  <!-- Google fonts - Muli-->
  <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Muli:300,400,700">

  <!-- Tweaks for older IEs--><!--[if lt IE 9]>
<script src="https://oss.maxcdn.com/html5shiv/3.7.3/html5shiv.min.js"></script>
<script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script><![endif]-->
  <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.7.1/css/all.css" integrity="sha384-fnmOCqbTlWIlj8LyTjo7mOUStjsKC4pOpQbqyi7RrhN7udi9RwhKkMHpvLbHG9Sr" crossorigin="anonymous">

  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>

  <%= stylesheet_link_tag "application", "default", "custom", "data-turbo-track": "reload" %>
  <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>
</head>

<body>
<% if controller_name === 'landing' %>
  <%= render 'layouts/header' %>
  <div class="page-content">
    <%= yield %>
  </div>
  <%= render 'layouts/footer' %>

<% elsif devise_controller? %>
  <%= yield %>

<% else %>
  <%= render 'layouts/header' %>
  <div class="d-flex align-items-stretch">
    <%= render 'layouts/sidebar' %>
    <div class="page-content">
      <%= render 'layouts/notices' %>
      <div class="container-fluid">
        <%= yield %>
      </div>
      <%= render 'layouts/footer' %>
    </div>
<% end %>
</div>
</body>
</html>